In [1]:
# from scripts.csv_processing import normalize_propforms
import pandas as pd
import re

## Rejoigner les fichiers pertinents pour sauvegarder les instances standards pour le projet

In [6]:
PATH_TO_DATA = '../data/external/ls-fr-V3.1'

FILES_REQUIRED = {
    'nodes': '01-lsnodes.csv',
    'entries': '02-lsentries.csv',
    'ex-rel': '18-lsex-rel.csv',
    'examples': '17-lsex.csv',
    'propforms': '11-lspropform-rel.csv',
    'pos': '06-lsgramcharac-rel.csv',
    'lfs': '15-lslf-rel.csv'
    } # les fichiers pertinents pour établir un tableau des FL exemples
def get_csv(filename, path=PATH_TO_DATA, separator='\t'):
    return pd.read_csv(f'{path}/{filename}', sep=separator)

### Combiner fichier des nodes et des entries

In [ ]:
nodes = get_csv(FILES_REQUIRED['nodes'])
nodes = nodes.rename(columns={'id': 'node_id', 'entry':'entry_id'})
print(nodes.shape)
nodes.head()

(29783, 8)

,node_id,entry_id,lexnum,status,%,update_date,update_time,lexname
0,ls:fr:node:26162,ls:fr:entry:26164,I.1,2,100,2021-03-13,09:45:08,<span class='namingform'>à</span><span class='...
1,ls:fr:node:26163,ls:fr:entry:26165,1,2,100,2017-03-07,08:28:24,<span class='namingform'>à propos</span><span ...
2,ls:fr:node:26164,ls:fr:entry:26166,II.2,2,100,2017-12-03,21:05:52,<span class='namingform'>abandonner</span><spa...
3,ls:fr:node:26166,ls:fr:entry:26168,I,2,100,2017-03-25,20:39:46,<span class='namingform'>abîme</span><span cla...
4,ls:fr:node:26167,ls:fr:entry:26169,I,2,100,2014-05-15,10:56:19,<span class='namingform'>abîmer</span><span cl...

In [8]:
entries = get_csv(FILES_REQUIRED['entries'])
# traiter les formes des lexies
entries['entry_name'] = entries.apply(lambda x: (str(x['addtoname']) + x['name']) if pd.notna(x['addtoname']) else x['name'], axis=1) # combiner les lexies avec les 'addtoname' puis les mettre dans 'entry_name'
entries = entries.rename(columns={'id': 'entry_id'})
print(entries.shape)
entries.head()

(18892, 8)

,entry_id,addtoname,name,subscript,superscript,status,%,entry_name
0,ls:fr:entry:26164,NaN,à,NaN,NaN,1,100,à
1,ls:fr:entry:26165,NaN,à propos,NaN,NaN,2,100,à propos
2,ls:fr:entry:26166,NaN,abandonner,NaN,NaN,2,100,abandonner
3,ls:fr:entry:26167,NaN,abeille,NaN,NaN,1,100,abeille
4,ls:fr:entry:26168,NaN,abîme,NaN,NaN,2,100,abîme

In [9]:
# Convert entry_id to match type between nodes and entries
nodes_entry = nodes.merge(entries[['entry_name', 'entry_id']], 
						 left_on='entry_id', 
						 right_on='entry_id', 
						 how='left')
print(nodes_entry.shape)
nodes_entry.head()

(29783, 9)

,node_id,entry_id,lexnum,status,%,update_date,update_time,lexname,entry_name
0,ls:fr:node:26162,ls:fr:entry:26164,I.1,2,100,2021-03-13,09:45:08,<span class='namingform'>à</span><span class='...,à
1,ls:fr:node:26163,ls:fr:entry:26165,1,2,100,2017-03-07,08:28:24,<span class='namingform'>à propos</span><span ...,à propos
2,ls:fr:node:26164,ls:fr:entry:26166,II.2,2,100,2017-12-03,21:05:52,<span class='namingform'>abandonner</span><spa...,abandonner
3,ls:fr:node:26166,ls:fr:entry:26168,I,2,100,2017-03-25,20:39:46,<span class='namingform'>abîme</span><span cla...,abîme
4,ls:fr:node:26167,ls:fr:entry:26169,I,2,100,2014-05-15,10:56:19,<span class='namingform'>abîmer</span><span cl...,abîmer

In [10]:
lfs = pd.read_csv('../data/interim/lfs_names_modified.csv')
lfs_names = lfs.set_index('lf_id')['lf_name'].to_dict()

In [11]:
def normalize_propforms(propform):
    """
    Fix some common bugs in propositional forms.
    Propositional forms starting with a "!" need to be validated.
    These "!" are removed and the propositional form is considered valid.
    """
    propform = re.sub(r"'", r'’', propform)
    propform = re.sub(r' +,', r',', propform)
    propform = re.sub(r'(\w)~', r'\1 ~', propform)
    propform = re.sub(r'~(\w)', r'~ \1', propform)
    propform = re.sub(r'\s\s+', r' ', propform)
    propform = re.sub(r'^! ?', r'', propform)
    return propform.strip()

propforms = get_csv(FILES_REQUIRED['propforms'])
propforms.propform = propforms.propform.apply(normalize_propforms)
propforms.set_index('node', inplace=True)
print(propforms.shape)
propforms.head()

(23399, 4)

                      propform tildevalue    %       actantslist
node
ls:fr:node:26162     [$1] ~ $2        NaN  100       ($1=X,$2=Y)
ls:fr:node:26163  [$1] ~ de $2        NaN  100       ($1=X,$2=Y)
ls:fr:node:26166             ~        NaN  100                ()
ls:fr:node:26167       $1 ~ $2     abîme   100       ($1=X,$2=Y)
ls:fr:node:26168  $1 ~ $2 à $3     abonne  100  ($1=X,$2=Y,$3=Z)

In [12]:
propforms[propforms.propform.str.contains('$')]

                                   propform tildevalue    %       actantslist
node
ls:fr:node:26162                  [$1] ~ $2        NaN  100       ($1=X,$2=Y)
ls:fr:node:26163               [$1] ~ de $2        NaN  100       ($1=X,$2=Y)
ls:fr:node:26166                          ~        NaN  100                ()
ls:fr:node:26167                    $1 ~ $2     abîme   100       ($1=X,$2=Y)
ls:fr:node:26168               $1 ~ $2 à $3     abonne  100  ($1=X,$2=Y,$3=Z)
...                                     ...        ...  ...               ...
ls:fr:node:56948                       $1 ~        NaN  100            ($1=X)
ls:fr:node:56949                       $1 ~        NaN  100            ($1=X)
ls:fr:node:56950  ~ utilisée par $1 pour $2        NaN  100       ($1=X,$2=Y)
ls:fr:node:56951   ~ utilisé par $1 pour $2        NaN  100       ($1=X,$2=Y)
ls:fr:node:56952    ~ où travaillent les $1        NaN  100            ($1=X)

[23399 rows x 4 columns]

In [13]:
def replace_actants(prop_f:str, actant_l:str):
    actants = actant_l.strip("()")
    mapping = dict(re.findall(r'(\$\d+)=(\w+)', actants))
    act_nums = [act_num for act_num in re.findall(r'\$\d+', prop_f)]
    for act_num in act_nums:
        if act_num in mapping:
            prop_f = prop_f.replace(act_num, mapping[act_num])
    
    return prop_f

def antantialize(df: pd.DataFrame):
    df = df.copy()
    df['actant_form'] = df.apply(lambda x: replace_actants(x['propform'], x['actantslist']), axis=1)
    df['actant_form'] = df.apply(lambda x: x['actant_form'].replace('~', str(x['tildevalue'])) if pd.notna(x['tildevalue']) else x['actant_form'], axis=1)
    return df
    
propforms = antantialize(propforms)

In [14]:
propforms.head()

,propform,tildevalue,%,actantslist,actant_form
node,,,,,
ls:fr:node:26162,[$1] ~ $2,NaN,100,"($1=X,$2=Y)",[X] ~ Y
ls:fr:node:26163,[$1] ~ de $2,NaN,100,"($1=X,$2=Y)",[X] ~ de Y
ls:fr:node:26166,~,NaN,100,(),~
ls:fr:node:26167,$1 ~ $2,abîme,100,"($1=X,$2=Y)",X abîme Y
ls:fr:node:26168,$1 ~ $2 à $3,abonne,100,"($1=X,$2=Y,$3=Z)",X abonne Y à Z

In [15]:
propforms.shape

(23399, 5)

## POS

In [21]:
preposition_id = ["ls:fr:gc:121", "ls:fr:gc:64", "ls:fr:gc:214"]
pos = get_csv(FILES_REQUIRED['pos'])
nodes_entry['POS'] = nodes_entry['node_id'].map(pos.set_index('node')['POS'])
nodes_entry[nodes_entry['POS'].isin(preposition_id)]

,node_id,entry_id,lexnum,status,%,update_date,update_time,lexname,entry_name,POS
0,ls:fr:node:26162,ls:fr:entry:26164,I.1,2,100,2021-03-13,09:45:08,<span class='namingform'>à</span><span class='...,à,ls:fr:gc:64
172,ls:fr:node:26341,ls:fr:entry:26343,I.1,2,100,2017-12-07,06:54:15,<span class='namingform'>après</span><span cla...,après,ls:fr:gc:64
564,ls:fr:node:26745,ls:fr:entry:26747,NaN,2,100,2014-07-15,10:49:26,<span class='namingform'>chez</span>,chez,ls:fr:gc:64
717,ls:fr:node:26899,ls:fr:entry:26901,II,2,100,2020-06-23,15:41:25,<span class='namingform'>contre</span><span cl...,contre,ls:fr:gc:64
811,ls:fr:node:26993,ls:fr:entry:26995,I.1,2,100,2017-06-11,14:00:01,<span class='namingform'>dans</span><span clas...,dans,ls:fr:gc:64
...,...,...,...,...,...,...,...,...,...,...
27344,ls:fr:node:54440,ls:fr:entry:44123,NaN,3,100,2016-12-05,08:57:47,<span class='namingform'>grâce</span><span cla...,grâce,ls:fr:gc:64
27934,ls:fr:node:55057,ls:fr:entry:27282,II.b,3,100,2020-08-13,15:31:24,<span class='namingform'>en</span><span class=...,en,ls:fr:gc:64
28179,ls:fr:node:55309,ls:fr:entry:29481,II.2,3,100,2018-01-22,16:52:37,<span class='namingform'>sous</span><span clas...,sous,ls:fr:gc:64
28192,ls:fr:node:55322,ls:fr:entry:27080,II,3,100,2018-01-18,09:44:50,<span class='namingform'>derrière</span><span ...,derrière,ls:fr:gc:64
28193,ls:fr:node:55323,ls:fr:entry:29481,III,3,100,2018-01-22,16:52:37,<span class='namingform'>sous</span><span clas...,sous,ls:fr:gc:64

## exemples et nodes

In [12]:
exemple_rel = get_csv(FILES_REQUIRED['ex-rel'])
# un node peut avoir plusieurs exemples
print(exemple_rel.shape)
exemple_rel.head()

(51056, 5)

               node        example occurrence  position    %
0  ls:fr:node:26162  ls:fr:ex:4328     66,67;         0  100
1  ls:fr:node:26162   ls:fr:ex:337   161,162;         1  100
2  ls:fr:node:26162   ls:fr:ex:331     37,38;         2  100
3  ls:fr:node:26162  ls:fr:ex:3964     26,27;         3  100
4  ls:fr:node:26162  ls:fr:ex:3348     53,54;         4  100

In [13]:
def get_keyword(df: pd.DataFrame, ex_col:str = "content", kw_seg_col: str = "occurrence"):
    """
    Get the keyword from the example.
    The keyword coresponds to the 
    """
    df

In [14]:
exemples = get_csv(FILES_REQUIRED['examples'])
print(exemples.shape)
exemples.head()

(32026, 8)

,id,source,status,content,title,authors,location,date
0,ls:fr:ex:13,ls:fr:exsrc:1,1,<html><body><p>Nous voulions kidnapper le géra...,Voyage au bout de la révolution : de Pékin à S...,"Brière-Blanchet, Claire",p. 116,2009
1,ls:fr:ex:14,ls:fr:exsrc:1,1,<html><body><p>Son patron lui a dit qu’il étai...,Journal 1977-1990,"Lagarce, Jean-Luc",p. 325,2007
2,ls:fr:ex:15,ls:fr:exsrc:1,1,<html><body><p>Elle a dit qu’elle t’avait cher...,Les Russkoffs,"Cavanna, François",p. 373,1979
3,ls:fr:ex:16,ls:fr:exsrc:2,1,<html><body><p>Les ravisseurs ont profité d’un...,NaN,NaN,http://www.yozone.fr/spip.php?article4460,02/2008
4,ls:fr:ex:17,ls:fr:exsrc:2,1,<html><body><p>Pour s’assurer que Jake lui rem...,NaN,NaN,http://tetelle43.blogs.allocine.fr/?blog=tetel...,02/2008

In [15]:
exemples.value_counts("status")

status
1    29985
0     2041
Name: count, dtype: int64

In [16]:
exemples=exemples.rename(columns={'id': 'ex_id'})
exemples.head()

,ex_id,source,status,content,title,authors,location,date
0,ls:fr:ex:13,ls:fr:exsrc:1,1,<html><body><p>Nous voulions kidnapper le géra...,Voyage au bout de la révolution : de Pékin à S...,"Brière-Blanchet, Claire",p. 116,2009
1,ls:fr:ex:14,ls:fr:exsrc:1,1,<html><body><p>Son patron lui a dit qu’il étai...,Journal 1977-1990,"Lagarce, Jean-Luc",p. 325,2007
2,ls:fr:ex:15,ls:fr:exsrc:1,1,<html><body><p>Elle a dit qu’elle t’avait cher...,Les Russkoffs,"Cavanna, François",p. 373,1979
3,ls:fr:ex:16,ls:fr:exsrc:2,1,<html><body><p>Les ravisseurs ont profité d’un...,NaN,NaN,http://www.yozone.fr/spip.php?article4460,02/2008
4,ls:fr:ex:17,ls:fr:exsrc:2,1,<html><body><p>Pour s’assurer que Jake lui rem...,NaN,NaN,http://tetelle43.blogs.allocine.fr/?blog=tetel...,02/2008

In [17]:
ex_content = exemples.set_index('ex_id')['content'].to_dict()
print(len(ex_content))
ex_content

32026

{'ls:fr:ex:13': '<html><body><p>Nous voulions kidnapper le gérant et le juger. Nous avions entamé une campagne de propagande contre «\xa0le gérant fasciste de Seyssinet\xa0».</p></body></html>',
 'ls:fr:ex:14': '<html><body><p>Son patron lui a dit qu’il était le seul de ses collaborateurs que les «\xa0chiites\xa0» ne garderaient pas plus de trois jours s’ils venaient à le kidnapper et qu’ils verseraient même une rançon pour le rendre.</p></body></html>',
 'ls:fr:ex:15': '<html><body><p>Elle a dit qu’elle t’avait cherché longtemps, que des troufions l’avaient kidnappée mais qu’elle s’était échappée, et alors elle est retournée là où vous étiez, et puis elle a parcouru le pays dans tous les sens en demandant après toi, et finalement, voilà, elle essayait de retarder son rapatriement le plus possible dans l’espoir que tu finirais par arriver...</p></body></html>',
 'ls:fr:ex:16': '<html><body><p>Les ravisseurs ont profité d’une absence de vigilance de la mère pour kidnapper la petite Amanda.</p></body></html>',
 'ls:fr:ex:17': '<html><body><p>Pour s’assurer que Jake lui remboursera bien tout l’argent qu’il lui doit, Johnny et sa bande kidnappent son petit frère, Zack.</p></body></html>',
 'ls:fr:ex:18': '<html><body><p>Les zaraguinas, qui parlent arabe, sont des voleurs de bétail visant principalement les tribus peules, qui sont relativement riches. Récemment, ils ont kidnappé des enfants contre rançon.</p></body></html>',
 'ls:fr:ex:19': '<html><body><p>Les deux adolescents meurtriers aujourd’hui âgés de 17 ans, Robert T. et Jon V., purgent en prison une période incompressible de huit ans pour avoir kidnappé et battu à mort le petit James, avant d’abandonner son corps sur une voie ferrée, près de Liverpool.</p></body></html>',
 'ls:fr:ex:20': '<html><body><p>Atteinte de graves troubles psychologiques, une femme retrouve, après une longue absence, sa fille devenue mère et fait la connaissance de son petit-fils. Mais l’enfant décède accidentellement et la grand-mère kidnappe un enfant pour l’offrir à sa fille.</p></body></html>',
 'ls:fr:ex:21': '<html><body><p>Et il débarquait, royal, dans le jeu de quilles quadrillé de nos amitiés, fonçant avec sa Jaguar pour kidnapper l’un d’entre nous et l’inviter à dîner dans un grand restaurant, ou déposant avec naturel comme offrande sur le pas de la porte où il s’imposait une caisse de mouton-rothschild qu’il avait payée quelques millions aux enchères à Drouot.</p></body></html>',
 'ls:fr:ex:23': '<html><body><p>«\xa0Ensemble Gradignan\xa0» est le «\xa0magazine d’information municipale de la ville de Gradignan\xa0». Allons-y pour «\xa0la ville\xa0» puisque nous avons un «\xa0hôtel de ville\xa0». Mais voilà que la liste conduite par Anne-Marie K. a kidnappé l’expression puisqu’elle s’intitule «\xa0Gradignan ensemble\xa0». Une (petite) inversion et le tour est joué !</p></body></html>',
 'ls:fr:ex:24': '<html><body><p>Donc, les européistes et les libéraux ont en quelque sorte kidnappé le mot « européen », pour en faire une chasse gardée qui recouvre quelque chose dont nous ne voulons pas. Parce que tous ces traités, à quoi visent-t-ils ? À faire l’Europe ? Non ! À faire un marché unique européen.</p></body></html>',
 'ls:fr:ex:25': '<html><body><p>M. L. n’a pu kidnapper à son seul profit la manifestation organisée dans le cadre de Meuse 2015. Privé légitimement de ce vedettariat par les décideurs meusiens, sa colère était manifeste lors du rassemblement à Bar-le-Duc.</p></body></html>',
 'ls:fr:ex:26': '<html><body><p>Une volée signée C. à la demi-heure de jeu, a suffi pour confondre une équipe parisienne incapable de convertir une seule de ses multiples occasions. Un authentique suicide tant la maladresse de la demi douzaine d’attaquants qui a terminé le match a frisé le ridicule. Le G., chaud comme une bouillotte, a kidnappé le match, laissant les Parisiens, indigents, s’enfoncer dans leurs malheurs.</p></body></html>',
 'ls:fr:ex:27': '<html><body><p>Ses protagonistes déclarent de concert qu’il n’y avait aucune sorte de volonté de complot dans leur attitude, ni même qu’ils s’étaient véritablement organisés pour kidnapper l’intérêt de cette assemblée générale.</p></body></html>',
 'ls:fr:ex:29': '<html><body><p>«\xa0Laisse-moi tranquille, on est samedi.\xa0»</p><p>«\xa0Non, Bella, je ne te laisserai pas tranquille. Je te kidnappe pour la journée.\xa0»</p><p>«\xa0Pardon\xa0?\xa0»</p><p>«\xa0J’ai décidé de t’emmener toute la journée avec moi.\xa0»</p></body></html>',
 'ls:fr:ex:30': '<html><body><p>«\xa0—\xa0J’ai oublié de te dire que je te kidnappe ce soir.</p><p>—\xa0Ah bon\xa0?</p><p>—\xa0Quel jour sommes-nous\xa0?</p><p>—\xa0Mardi... Désolé.</p><p>—\xa0Hm. Donc ce soir tu es uniquement à moi.</p><p>—\xa0Sans problèmes.</p><p>Il s’approcha d’elle, l’embrassa et lui chuchota à l’oreille\xa0:</p><p>—\xa0Joyeux anniversaire d’amour.\xa0»</p></body></html>',
 'ls:fr:ex:31': '<html><body><p>Migmar ne savait pas que je venais ce soir-là, mais il m’a tout de suite repérée, haut perchée au dernier étage du monastère. Il m’a kidnappée pour que je lui montre toutes les photos de Lumbini, et puis on a fini par regarder toutes les photos de nos voyages respectifs. Beaucoup plus sensible à la beauté sauvage, l’architecture de Prague et de Montréal l’ont laissé de marbre, alors que ses photos de pèlerinage en Inde m’ont complètement transportée.</p></body></html>',
 'ls:fr:ex:32': '<html><body><p>Je dépasse enfin la porte de Saint-Cloud pour aller voir mon ami Simon, immobilisé par une fracture chez ses grands-parents, à La Motte-Picquet-Grenelle.</p></body></html>',
 'ls:fr:ex:33': '<html><body><p>Avant la guerre, à Tours, tu avais deux amis, l’un s’appelait Marcel, l’autre Paul. Tu aimais le premier, le second était amoureux de toi.</p></body></html>',
 'ls:fr:ex:34': '<html><body><p>Dans le fond de la salle, les personnes qui n’avaient pas de place assise, entassées. Le poulailler. J’y reconnus aussi certains amis, camarades ou relations.</p></body></html>',
 'ls:fr:ex:35': '<html><body><p>Le médecin dieppois, fortement attaché à sa région, a donné de ses nouvelles à un collègue et ami d’enfance.</p></body></html>',
 'ls:fr:ex:36': '<html><body><p>Chez moi je n’avais pas de platine juste une boîte en plastique avec 20 disques. Je séchais les cours pour m’entraîner chez un ami avant les soirées.</p></body></html>',
 'ls:fr:ex:38': '<html><body><p>Connaît-on vraiment ses parents, ses anciennes amours, ses enfants, ses amis\xa0?</p></body></html>',
 'ls:fr:ex:39': '<html><body><p>À la suite de quelques sessions de musique pop folk, les trois amis décident, en décembre, de former un petit groupe pour partager avec les autres leur passion pour la musique irlandaise.</p></body></html>',
 'ls:fr:ex:40': '<html><body><p>En se côtoyant quotidiennement, ils devinrent même de vrais amis. Quand on voit l’un, l’autre n’est pas loin.</p></body></html>',
 'ls:fr:ex:41': '<html><body><p>Au cours de ce spectacle de nombreux parents et amis sont venus applaudir la prestation des enfants.</p></body></html>',
 'ls:fr:ex:42': '<html><body><p>Moi aussi, j’ai mon ami... non, c’est mon mari maintenant, de l’autre côté.</p></body></html>',
 'ls:fr:ex:43': '<html><body><p>Avec ses bagages, ses deux filles et son nouvel ami, Graciela débarque chez un copain de Miguel, l’un de ses frères aînés.</p></body></html>',
 'ls:fr:ex:44': '<html><body><p>Il me confia qu’il traversait l’inconvénient de se trouver à la lisière de deux appartements et de devoir en visiter chaque jour de nouveaux, de ne pouvoir disposer de ses livres entassés dans des caisses, il avait quitté son ami avec lequel il avait vécu plus de dix ans, et, ajouta-t-il en rougissant, «\xa0mon nouvel ami s’appelle comme vous\xa0», et il prononça mon prénom.</p></body></html>',
 'ls:fr:ex:45': '<html><body><p>«\xa0Qui m’aime me suive\xa0!\xa0», c’est l’histoire d’Ellen qui vient de rompre avec son ami qu’elle croyait célibataire et qui était en réalité marié et père de famille\xa0!</p></body></html>',
 'ls:fr:ex:46': '<html><body><p>Bonjour à vous, mon ami et moi sommes en passe d’acheter une maison dans le Brabant-Wallon.</p></body></html>',
 'ls:fr:ex:47': '<html><body><p>Et au delà de la tromperie, ton histoire ressemble plus à un fantasme. Peut-être qu’en le voyant, tu n’auras pas du tout envie de tromper ton ami.</p></body></html>',
 'ls:fr:ex:48': '<html><body><p>«\xa0Il souffre et il a d’autant plus de mal à faire le deuil de son mariage que son épouse vit avec son nouvel ami à 500 m de chez lui. C’est un homme blessé. Il n’est peut-être pas utile d’en rajouter », plaide Me G.</p></body></html>',
 'ls:fr:ex:49': '<html><body><p>Il devait être mis en examen pour viol suite à la plainte déposée par son ex-concubine, âgée de 20 ans, qui a confié aux policiers que son ancien ami lui avait imposé une relation sexuelle qu’elle ne désirait pas.</p></body></html>',
 'ls:fr:ex:50': '<html><body><p>Ayant rencontré quelqu’un d’autre, elle veut refaire sa vie. Mais l’amoureux éconduit ne l’entend pas de cette façon. Il décide alors d’envoyer plusieurs courriers anonymes au procureur, au commissaire central, au maire d’Audincourt et même au président de la République. Des lettres dans lesquelles il dénonce la belle comme étant au cœur d’un trafic de stupéfiants. Il cite même les références de la voiture du nouvel ami de son ex-fiancée comme celle d’un trafiquant notoire.</p></body></html>',
 'ls:fr:ex:51': '<html><body><p>J’ai assez d’amis haut placés pour raccourcir au maximum son purgatoire à Hénin-Liétard ou à Eygurande-Merlines.</p></body></html>',
 'ls:fr:ex:52': '<html><body><p>Deux précisions\xa0: d’abord, depuis le début de la guerre au Vietnam, j’étais contre à cent pour cent\xa0; ensuite, j’avais de bons amis dans le corps diplomatique et parmi les hommes d’affaires de plusieurs pays, grâce auxquels j’avais pu recueillir d’abondantes informations sur la guerre, inconnues du grand public.</p></body></html>',
 'ls:fr:ex:53': '<html><body><p>Tu agitais mille projets\xa0: trouver un appartement à la lisière d’un bois, choisir une école primaire où je pourrais côtoyer des garçons de toutes les couches sociales sans pourtant me commettre avec des fils d’ouvriers, offrir tes services à des organisateurs de concerts, te faire des amis dans les milieux musicaux, aider mon père à développer son commerce de timbres-poste jusqu’au jour où il pourrait se permettre de prendre une secrétaire.</p></body></html>',
 'ls:fr:ex:54': '<html><body><p>La lecture de la presse laisse entendre qu’il n’avait pas que des amis auprès des grandes institutions lyriques...</p></body></html>',
 'ls:fr:ex:56': '<html><body><p>À l’inverse, ceux qui n’ont pas d’amis bien placés vont subir la pression des procureurs et risquent d’avouer des faits qu’ils n’ont pas commis.</p></body></html>',
 'ls:fr:ex:57': '<html><body><p>En outre, Yvan C. connaît parfaitement sa région et peut compter sur un vaste réseau d’amis, susceptibles de l’aider à tromper la vigilance des enquêteurs engagés dans une véritable chasse à l’homme depuis que certains membres du commando ont désigné C. comme celui qui aurait abattu le préfet E.</p></body></html>',
 'ls:fr:ex:58': '<html><body><p>Après l’école Marie-Curie, Olivier avait fréquenté le collège Robert-Delaunay, se tissant, à chaque étape, un important réseau d’amis.</p></body></html>',
 'ls:fr:ex:59': '<html><body><p>En fin de saison dernière, le comité avait décidé de confier les commandes de l’équipe fanion à Jean-Claude H., ce dernier présentant l’avantage de coûter deux fois moins cher que Bernard D. Seulement voilà, l’ancien entraîneur du club et de Gérardmer n’avait pas que des amis dans la boutique.</p></body></html>',
 'ls:fr:ex:60': '<html><body><p>Mais les officiels insistèrent fermement\xa0: «\xa0Si vous êtes des amis du peuple chinois, vous devez lire comme le peuple, à l’exemple du président Mao et de Lin Biao, le Petit Livre rouge\xa0».</p></body></html>',
 'ls:fr:ex:61': '<html><body><p>Je me sens l’âme bucolique. Je vis «\xa0pour de vrai\xa0» le rêve sportif du campeur à pied, du joyeux ami de la nature, tel que je le voyais à travers les enthousiasmes de Bob Lavignon et des autres fervents des Auberges de Jeunesse.</p></body></html>',
 'ls:fr:ex:62': '<html><body><p>Sur le plan national, elle rassemble autour d’elle, dans une société, les «\xa0amis de la phonothèque nationale\xa0» qui organisent des conférences avec audition de disques anciens.</p></body></html>',
 'ls:fr:ex:63': '<html><body><p>Serait-ce un moyen pour les solitaires et amis de la plume de s’exprimer sans se faire couper la parole\xa0?</p></body></html>',
 'ls:fr:ex:64': '<html><body><p>Dans ces moments difficiles (nous en avons connu beaucoup et c’est toujours beaucoup trop), je veux dire à tous les amis de la gauche que nous devons continuer de croire et de nous battre.</p></body></html>',
 'ls:fr:ex:65': '<html><body><p>L’amour de la chasse, de la nature et l’intérêt pour les nouvelles technologies nous ont amené à vouloir concilier «\xa0chasse\xa0» et «\xa0communication\xa0». Par communication, nous entendons «\xa0ouverture\xa0», «\xa0dialogue\xa0» entre tous les chasseurs, amis de la chasse et de la nature, afin que tous soyons rassemblés autour d’un message fort\xa0: «\xa0préservons la chasse &amp; communiquons notre passion\xa0».</p></body></html>',
 'ls:fr:ex:66': '<html><body><p>Nous cherchons en effet des amis d’Emmaüs, des personnes capables de donner un peu de leur temps pour partager avec les compagnons la tâche quotidienne mais aussi les loisirs.</p></body></html>',
 'ls:fr:ex:67': '<html><body><p>En clair, pour permettre aux équipes du RCP de participer aux différentes compétitions, il faut de l’argent afin de payer les bus. Voilà une des raisons qui poussent chaque année le club de rugby à organiser un super bingo dont les bénéfices servent à financer ces voyages. Une autre raison\xa0: permettre à tous les amis de l’ovalie de se retrouver à la salle socio-culturelle pour célébrer ensemble le culte de l’ovalie.</p></body></html>',
 'ls:fr:ex:68': '<html><body><p>Ce samedi 23 février, les amis de la nature organisent une sortie photo.</p></body></html>',
 'ls:fr:ex:69': '<html><body><p>Quand la dame de ménage arrive, elle se demande ce qu’il reste à faire, à quoi elle va bien pouvoir s’occuper pour mériter salaire dans cette maison propre comme un sou neuf jusque dans les coins.</p></body></html>',
 'ls:fr:ex:70': '<html><body><p>L’ordre S.S. exigeait que l’on se déplaçât à l’intérieur des baraques avec des chaussures propres. Les jours de pluie et de boue, ce n’était pas facile d’y parvenir.</p></body></html>',
 'ls:fr:ex:71': '<html><body><p>Quand il ne fait pas trop froid, ma grand-mère sort son échelle de l’appentis, elle me donne une éponge et une bassine d’eau mousseuse. Juchée sur mon échelle, je lave les carrelages à grande eau. Peu d’activités donnent autant de plaisir, sans compter qu’à la fin du jeu, le carrelage est propre.</p></body></html>',
 'ls:fr:ex:72': '<html><body><p>Miss Hogge et sa sœur ne doivent pas être riches. Elles prennent locataires pour obtenir un petit revenu supplémentaire. La maison est propre, mais très simple et même un peu sommaire, visiblement pas renouvelée depuis vingt ans.</p></body></html>',
 'ls:fr:ex:73': '<html><body><p>Par mesure d’hygiène, les peluches ou les « doudous » sont acceptés en maternelle s’ils sont propres et régulièrement lavés.</p></body></html>',
 'ls:fr:ex:74': '<html><body><p>En excellent état, les chambres sont propres et belles, avec des couvre-lits fleuris et des couleurs pastel. Le mobilier y est moderne. Elles sont assez petites mais confortables...</p></body></html>',
 'ls:fr:ex:75': '<html><body><p>Les utilisateurs de camping-cars et de caravanes y trouveront une place, mais les arbres tortueux ne faciliteront pas leurs manœuvres. Les sanitaires y sont propres, les douches chaudes payantes.</p></body></html>',
 'ls:fr:ex:76': '<html><body><p>Les panneaux publicitaires sont interdits. Jean-Louis T. a dû remiser une enseigne lumineuse, la sobriété étant de rigueur sur les façades. Les poubelles aussi sont proscrites : « Pourquoi ne pas en fixer sur les panneaux de circulation ? », interroge le commerçant, qui en attendant de convaincre ceux « d’en face », à l’Hôtel de ville, rend hommage aux services d’entretien : « Chapeau ! La place est très propre, super bien entretenue ».</p></body></html>',
 'ls:fr:ex:77': '<html><body><p>« J’aurai été surpris, ils ont totalement respecté leur engagement, le pasteur est venu payer l’eau et l’enlèvement des ordures ménagères, et il m’avait promis leur départ pour le dimanche. Ce qui a été fait, et bien fait, le terrain a été laissé parfaitement propre. »</p></body></html>',
 'ls:fr:ex:78': '<html><body><p>La législation française le prévoit : les entreprises doivent mettre à la disposition de leur personnel un morceau de tissu propre et sec pour se laver les mains.</p></body></html>',
 'ls:fr:ex:79': '<html><body><p>Les quartiers blancs de toutes les villes coloniales du monde étaient toujours, dans ces années-là, d’une impeccable propreté. Il n’y avait pas que les villes. Les blancs aussi étaient très propres. Dès qu’ils arrivaient, ils apprenaient à se baigner tous les jours, comme on fait des petits enfants, et à s’habiller de l’uniforme colonial, du costume blanc, couleur d’immunité et d’innocence.</p></body></html>',
 'ls:fr:ex:80': '<html><body><p>Il est toujours propre, changeant de costume le lundi et le vendredi et, tout comme Vireil, porte des bottines que d’ailleurs, tout comme Vireil, il enlève pour mieux courir pendant la récréation.</p></body></html>',
 'ls:fr:ex:81': '<html><body><p>Aureliano Romero était tout ce qu’on voudra, honnête, très propre dans tous les sens du mot, soigné, assez beau, intelligent à sa façon, digne de toutes les confiances\xa0—\xa0mais il n’était, à coup sûr, ni effervescent ni pyrotechnique.</p></body></html>',
 'ls:fr:ex:82': '<html><body><p>Pas les films habituels où le cow-boy est toujours propre et bon ou méchant mais au contraire le western sale, poussiéreux où les hommes ne se lavent pas et où l’on tue de sang-froid sans beau discours.</p></body></html>',
 'ls:fr:ex:83': '<html><body><p>« La promiscuité, des conditions de vie sommaires mais, malgré tout, des gens très dignes et propres », c’est l’image de l’Albanie et de ses réfugiés kosovars que rapporte Élisabeth M., partie à Tirana avec le convoi « Besançon ».</p></body></html>',
 'ls:fr:ex:86': '<html><body><p>Plusieurs chatons de type européen sont à placer. Ils sont âgés de 4 à 12 mois, sont propres et éduqués. Les plus âgés seront stérilisés par la SPA.</p></body></html>',
 'ls:fr:ex:87': '<html><body><p>Un enfant est propre s’il a compris le plaisir d’avoir une culotte au lieu d’une couche, de se sentir bien. L’école ne doit pas être l’enjeu de la propreté.</p></body></html>',
 'ls:fr:ex:88': '<html><body><p>Les inscriptions à l’école maternelle « les enfants Guerquin » auront lieu, le samedi 5 juin, de 9h à 11h30. Se munir du carnet de santé, d’un certificat médical d’aptitude à entrer à l’école et d’une fiche d’État civil. Conditions requises : l’enfant doit être propre et avoir 2 ans avant le 31 décembre 99.</p></body></html>',
 'ls:fr:ex:89': '<html><body><p>La victime a 11 ans lorsque les événements se sont déroulés dans le petit appartement de Montbéliard, courant juillet 97. Du jour au lendemain, le jeune garçon change de comportement. D’un esprit vif et jovial, il se replie sur lui-même, régresse soudainement, cessant d’être propre et passant parfois des journées entières à scruter un mur sans dire un mot.</p></body></html>',
 'ls:fr:ex:90': '<html><body><p>« Mon chien, il est propre, il ne fait jamais ses besoins sur le trottoir ! »</p></body></html>',
 'ls:fr:ex:91': '<html><body><p>Urgent, cause séparation, donne chatte British shorthair, robe bleue, née en septembre 2001, vaccinée, tatouée, propre et affectueuse !</p></body></html>',

In [18]:
exemple_rel['content'] = exemple_rel['example'].map(ex_content)
# exemple_rel = exemple_rel.merge(nodes_entry[['node_id', 'entry_name']], 
#                   left_on='node', 
#                   right_on='node_id', 
#                   how='left', 
#                   suffixes=('', '_entry'))
# exemple_rel = exemple_rel[["node", "example", "entry_name", "content", "occurrence", "position"]]
print(exemple_rel.shape)

# We only keep the first example for each node, witch is the most relevant one
exemple_rel = exemple_rel[exemple_rel['position'] == 0].copy()
print(exemple_rel.shape)
exemple_rel.head()

(51056, 6)
(27811, 6)

,node,example,occurrence,position,%,content
0,ls:fr:node:26162,ls:fr:ex:4328,"66,67;",0,100,<html><body><p>C’est comme de changer d’avion ...
9,ls:fr:node:26163,ls:fr:ex:4628,"62,70;",0,100,"<html><body><p>Le docteur Ricci, que maman m’a..."
11,ls:fr:node:26164,ls:fr:ex:1323,"48,57;",0,100,<html><body><p>Pourtant un jour elle partit et...
12,ls:fr:node:26166,ls:fr:ex:10465,"203,208;",0,100,<html><body><p>De nombreux Constantinois allai...
13,ls:fr:node:26167,ls:fr:ex:11675,"150,155;",0,100,<html><body><p>« On remplit au fur et à mesure...

In [19]:
def highlight_by_positions(sentence: str, positions_str: str, wrapper=("【", "】")):
    if pd.isna(positions_str) or not positions_str.strip():
        return sentence

    # 处理位置字符串
    positions = []
    for pos in positions_str.strip(";").split(";"):
        if "," in pos:
            try:
                start, end = map(int, pos.split(","))
                positions.append((start - 1, end - 1))  # 包含终止字符
            except:
                continue

    # 从后往前插入，防止坐标错乱
    positions.sort(reverse=True, key=lambda x: x[0])

    for start, end in positions:
        if 0 <= start < end <= len(sentence):
            sentence = sentence[:start] + wrapper[0] + sentence[start:end] + wrapper[1] + sentence[end:]
    return sentence

In [20]:
exemple_rel['ex_highlighted'] = exemple_rel.apply(
    lambda row: highlight_by_positions(row['content'], row['occurrence']),
    axis=1
)
bop = "<html><body><p>"
eop = "</p></body></html>"
exemple_rel['ex_highlighted'] = exemple_rel['ex_highlighted'].str.replace(bop, '').str.replace(eop, '')
exemple_rel_dict = exemple_rel.set_index('node')["ex_highlighted"].to_dict()
exemple_rel.head().to_csv('../data/interim/exemples_highlighted.csv', index=False)

In [21]:
lfs_rel = get_csv(FILES_REQUIRED['lfs'])
print(lfs_rel.columns)
print(lfs_rel.shape)
lfs_instances = lfs_rel[['lf', 'source', 'target','form','merged']].copy()
lfs_instances.head()

Index(['source', 'lf', 'target', 'form', 'separator', 'merged',
       'syntacticframe', 'constraint', 'position'],
      dtype='object')
(65489, 9)

           lf            source            target form  merged
0  ls:fr:lf:3  ls:fr:node:26162  ls:fr:node:43890  NaN       0
1  ls:fr:lf:3  ls:fr:node:26162  ls:fr:node:41336  NaN       0
2  ls:fr:lf:3  ls:fr:node:26162  ls:fr:node:29809  NaN       0
3  ls:fr:lf:3  ls:fr:node:26163  ls:fr:node:32392  NaN       0
4  ls:fr:lf:3  ls:fr:node:26163  ls:fr:node:32518  NaN       0

In [22]:
# combine
lfs_instances['lf_name'] = lfs_instances['lf'].map(lfs_names)
lfs_instances = lfs_instances[['lf', 'lf_name', 'source', 'target', 'form', 'merged']]
lfs_instances.head()

           lf lf_name            source            target form  merged
0  ls:fr:lf:3   Syn_∩  ls:fr:node:26162  ls:fr:node:43890  NaN       0
1  ls:fr:lf:3   Syn_∩  ls:fr:node:26162  ls:fr:node:41336  NaN       0
2  ls:fr:lf:3   Syn_∩  ls:fr:node:26162  ls:fr:node:29809  NaN       0
3  ls:fr:lf:3   Syn_∩  ls:fr:node:26163  ls:fr:node:32392  NaN       0
4  ls:fr:lf:3   Syn_∩  ls:fr:node:26163  ls:fr:node:32518  NaN       0

In [23]:
# if source == target
lfs_instances[lfs_instances['source'] == lfs_instances['target']]

,lf,lf_name,source,target,form,merged
883,ls:fr:lf:845,ClausCaus_1Pred,ls:fr:node:26370,ls:fr:node:26370,« ~ ! »,0
2396,ls:fr:lf:40,S_2,ls:fr:node:26668,ls:fr:node:26668,~,0
3463,ls:fr:lf:385,Result_2,ls:fr:node:26854,ls:fr:node:26854,NaN,1
4623,ls:fr:lf:40,S_2,ls:fr:node:27109,ls:fr:node:27109,~,0
4769,ls:fr:lf:68,S_med,ls:fr:node:27142,ls:fr:node:27142,~,0
...,...,...,...,...,...,...
64227,ls:fr:lf:40,S_2,ls:fr:node:56430,ls:fr:node:56430,~,0
64252,ls:fr:lf:40,S_2,ls:fr:node:56440,ls:fr:node:56440,~,0
64550,ls:fr:lf:40,S_2,ls:fr:node:56523,ls:fr:node:56523,~,0
64990,ls:fr:lf:31,S_1,ls:fr:node:56703,ls:fr:node:56703,~,0
65018,ls:fr:lf:69,S_res,ls:fr:node:56716,ls:fr:node:56716,~,0

In [26]:
lfs_instances.shape

(65489, 7)

In [27]:
# 添加每个function的keywords和values
node_id_to_entry_name = nodes_entry.set_index('node_id')['entry_name'].to_dict()
lfs_instances['keywords'] = lfs_instances['source'].map(node_id_to_entry_name)
lfs_instances['values'] = lfs_instances['target'].map(node_id_to_entry_name)
lfs_instances["kw_context"] = lfs_instances["source"].map(exemple_rel_dict)
lfs_instances

,lf,lf_name,source,target,form,merged,propform,keywords,values,kw_context
0,ls:fr:lf:3,Syn_∩,ls:fr:node:26162,ls:fr:node:43890,NaN,0,[X] ~ Y,à,en direction,C’est comme de changer d’avion à Milan pour al...
1,ls:fr:lf:3,Syn_∩,ls:fr:node:26162,ls:fr:node:41336,NaN,0,[X] ~ Y,à,sur,C’est comme de changer d’avion à Milan pour al...
2,ls:fr:lf:3,Syn_∩,ls:fr:node:26162,ls:fr:node:29809,NaN,0,[X] ~ Y,à,vers,C’est comme de changer d’avion à Milan pour al...
3,ls:fr:lf:3,Syn_∩,ls:fr:node:26163,ls:fr:node:32392,NaN,0,[X] ~ de Y,à propos,au sujet,"Le docteur Ricci, que maman m’avait mené voir ..."
4,ls:fr:lf:3,Syn_∩,ls:fr:node:26163,ls:fr:node:32518,NaN,0,[X] ~ de Y,à propos,concernant,"Le docteur Ricci, que maman m’avait mené voir ..."
...,...,...,...,...,...,...,...,...,...,...
65484,ls:fr:lf:455,S_1CausFunc_0,ls:fr:node:56951,ls:fr:node:37921,NaN,0,~ utilisé par X pour Y,solaire,soleil,"Le plus intéressant, rapide à mettre en place ..."
65485,ls:fr:lf:239,S_0Real_1,ls:fr:node:56951,ls:fr:node:56952,NaN,1,~ utilisé par X pour Y,solaire,solaire,"Le plus intéressant, rapide à mettre en place ..."
65486,ls:fr:lf:1089,Gener_⊃,ls:fr:node:56952,ls:fr:node:27929,NaN,0,~ où travaillent les X,solaire,industrie,Le 【solaire】 se développe rapidement : le taux...
65487,ls:fr:lf:68,S_med,ls:fr:node:56952,ls:fr:node:56950,NaN,0,~ où travaillent les X,solaire,énergie solaire,Le 【solaire】 se développe rapidement : le taux...
65488,ls:fr:lf:68,S_med,ls:fr:node:56952,ls:fr:node:56951,NaN,0,~ où travaillent les X,solaire,solaire,Le 【solaire】 se développe rapidement : le taux...

In [28]:
node_to_propform = propforms['actant_form'].to_dict()
lfs_instances['propform'] = lfs_instances['source'].map(node_to_propform)
lfs_instances

,lf,lf_name,source,target,form,merged,propform,keywords,values,kw_context
0,ls:fr:lf:3,Syn_∩,ls:fr:node:26162,ls:fr:node:43890,NaN,0,[X] ~ Y,à,en direction,C’est comme de changer d’avion à Milan pour al...
1,ls:fr:lf:3,Syn_∩,ls:fr:node:26162,ls:fr:node:41336,NaN,0,[X] ~ Y,à,sur,C’est comme de changer d’avion à Milan pour al...
2,ls:fr:lf:3,Syn_∩,ls:fr:node:26162,ls:fr:node:29809,NaN,0,[X] ~ Y,à,vers,C’est comme de changer d’avion à Milan pour al...
3,ls:fr:lf:3,Syn_∩,ls:fr:node:26163,ls:fr:node:32392,NaN,0,[X] ~ de Y,à propos,au sujet,"Le docteur Ricci, que maman m’avait mené voir ..."
4,ls:fr:lf:3,Syn_∩,ls:fr:node:26163,ls:fr:node:32518,NaN,0,[X] ~ de Y,à propos,concernant,"Le docteur Ricci, que maman m’avait mené voir ..."
...,...,...,...,...,...,...,...,...,...,...
65484,ls:fr:lf:455,S_1CausFunc_0,ls:fr:node:56951,ls:fr:node:37921,NaN,0,~ utilisé par X pour Y,solaire,soleil,"Le plus intéressant, rapide à mettre en place ..."
65485,ls:fr:lf:239,S_0Real_1,ls:fr:node:56951,ls:fr:node:56952,NaN,1,~ utilisé par X pour Y,solaire,solaire,"Le plus intéressant, rapide à mettre en place ..."
65486,ls:fr:lf:1089,Gener_⊃,ls:fr:node:56952,ls:fr:node:27929,NaN,0,~ où travaillent les X,solaire,industrie,Le 【solaire】 se développe rapidement : le taux...
65487,ls:fr:lf:68,S_med,ls:fr:node:56952,ls:fr:node:56950,NaN,0,~ où travaillent les X,solaire,énergie solaire,Le 【solaire】 se développe rapidement : le taux...
65488,ls:fr:lf:68,S_med,ls:fr:node:56952,ls:fr:node:56951,NaN,0,~ où travaillent les X,solaire,solaire,Le 【solaire】 se développe rapidement : le taux...

## Calculer le score levenstein

In [ ]:
import Levenshtein
def get_levenshtein_distance(s1, s2):
    """
    Calculate the Levenshtein distance between two strings.
    """
    return Levenshtein.distance(s1, s2)
def get_levenshtein_ratio(s1, s2):
    """
    Calculate the Levenshtein ratio between two strings.
    """
    return Levenshtein.ratio(s1, s2)

In [30]:
lfs_instances['levenshtein_distance'] = lfs_instances.apply(
	lambda row: get_levenshtein_distance(row['keywords'], row['values']), axis=1
)
lfs_instances['levenshtein_ratio'] = lfs_instances.apply(
	lambda row: get_levenshtein_ratio(row['keywords'], row['values']), axis=1
)
lfs_instances['levenshtein_distance'] = lfs_instances['levenshtein_distance'].astype(int)
lfs_instances['levenshtein_ratio'] = lfs_instances['levenshtein_ratio'].astype(float)
print(lfs_instances['levenshtein_distance'].describe())
print(lfs_instances['levenshtein_ratio'].describe())

count    65489.000000
mean         6.332331
std          3.795735
min          0.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         64.000000
Name: levenshtein_distance, dtype: float64
count    65489.000000
mean         0.429185
std          0.262486
min          0.000000
25%          0.222222
50%          0.363636
75%          0.625000
max          1.000000
Name: levenshtein_ratio, dtype: float64

In [74]:
ex_mapping = exemple_rel.set_index('content')['node'].to_dict()
len(ex_mapping)

20776

In [75]:
print(lfs_instances.shape)
print(nodes_entry.shape)
print(exemples.shape)

(65489, 10)
(29783, 9)
(32026, 8)

In [77]:
lfs_instances = lfs_instances.drop(columns=['source', 'target'])

In [78]:
lfs_instances.dropna(subset=['propform'], inplace=True)

In [80]:
lfs_instances = lfs_instances.applymap(lambda x: str(x).replace('\u2028', ' ').replace('\u2029', ' ') if isinstance(x, str) else x)
lfs_instances.shape

/tmp/ipykernel_380892/2966231895.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  lfs_instances = lfs_instances.applymap(lambda x: str(x).replace('\u2028', ' ').replace('\u2029', ' ') if isinstance(x, str) else x)

(55571, 8)

In [ ]:
# lfs_instances.to_csv('outputs/lfs_instances_propform_cleaned.csv', index=False)

In [13]:
# Exemple of instances
import pandas as pd
lfs_instances = pd.read_csv('../data/processed/lfs-slctd.csv')
lfs_instances.head()
lfs_instances_sp = lfs_instances[["index","lf_id", "lf_name", "keyword", "value", "kw_propform", "vl_propform", "kw_context"]]
ex = lfs_instances_sp[lfs_instances_sp['index'].isin([415, 42, 11516, 3806, 4961])].drop(columns=['index'])
ex.to_csv('../data/interim/lfs_instances_examples.csv', index=False)